apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::561280045991:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-5VNV3HPDQCU1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::561280045991:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-16T17:25:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1536"
  uid: 55292423-d586-4ab7-a063-b763e234f72a
